@startuml
'https://plantuml.com/sequence-diagram


actor Client as c
participant "Website Registration page" as wrp
participant CreateUserAccountActivity as cua
database UserAccounts

c -> wrp: Submit User Registration Form
wrp -> cua: Send User Account Information
cua -> UserAccounts: save new UserAccount
@enduml